config/routes.rb
Rails.application.routes.draw do

  get '/home',      to: 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/search',    to: 'movies#search'
  get '/apicreate', to: 'movies#apicreate'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'log_out', to: 'devise/sessions#destroy'
    get 'edit',    to: 'devise/registrations#edit'
  end

  post 'friendship', to: 'friendships#create'
  delete 'friendship', to: 'friendships#destroy'
  resources :users, only: [:index, :show]
  resources :movies
  resources :user_movies, except: [:destroy, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/movies_controller.rb
# encoding: utf-8
class MoviesController < ApplicationController
  before_action :set_movie, only: [:edit, :update, :destroy]

  # GET /movies
  # GET /movies.xml
  def index
    @movies = Movie.all
  end

  # GET /movies/new
  # GET /movies/new.xml
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def show
    @movie = Movie.find(params[:id])
    unless @movie.blank?
      if user_signed_in?
        @addedmovie = UserMovie.find_by(user_id: current_user.id, movie_id: @movie.id)
      end
    end
  end

  # POST /movies
  # POST /movies.xml
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.xml
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
      else
        format.html { redirect_to edit_movie_path(@movie), notice: 'Movie was not updated.'}
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.xml
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @movies, @moviesAPI = Movie.search(params[:searchterm])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def apicreate
    @movie = Movie.add_from_api(params[:imdbid])
    redirect_to @movie
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end
    def movie_params
      params.require(:movie).permit(:title, :poster, :year, :plot, :director, :language, :metascore, :release_date)
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :plot %><br>
    <%= f.text_field :plot %>
  </div>
    <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
    <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
    <div class="field">
    <%= f.label :metascore %><br>
    <%= f.text_field :metascore %>
  </div>
    <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% provide(:title, 'Movies') %>
<p id="notice"> <% notice %></p>

<div class="center jumbotron">
  <h1>Popular Movies</h1>

  <tbody>
    <% @movies.each do |movie| %>     
        <h2><%= link_to movie.title, movie %></h2>    
    <% end %>
  </tbody>
</div>

app/views/movies/new.html.erb
<% provide(:title, 'Add a movie') %>
<h1>New Movie</h1>

<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :plot %><br>
    <%= f.text_field :plot %>
  </div>
    <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
    <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
    <div class="field">
    <%= f.label :metascore %><br>
    <%= f.text_field :metascore %>
  </div>
    <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<% provide(:title, 'Search') %>

<% unless @movies.blank? && @moviesAPI.blank? %>
	<% @movies.each do |movie| %>
		<h1><%= link_to movie.title, movie %></h1>
	<% end %>
	<h1>API CALL</h1>
	<% @moviesAPI.each do |movie| %>
		<h1><%= link_to movie['Title'], apicreate_path(imdbid: movie['imdbID']) %></h1>
	<% end %>
<% else %>
	<h2> There are no Movies that match your criteria</h2>
	<div class="center">
		<%= link_to "Your movie exist? Create it here and expand the database", 'movies/new', class: "btn btn-lg btn-primary" %>
	</div>
	<% end %>

app/views/movies/show.html.erb
<div class="center jumbotron">
<p>
  <img src="<%= @movie.poster %>" style="width: 200px">
</p>
<p>
  <strong>Title:</strong><br>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong><br>
  <%= @movie.year %>
</p>

<p>
  <strong>Plot:</strong><br>
  <%= @movie.plot %>
</p>
<p>
  <strong>Director:</strong><br>
  <%= @movie.director %>
</p>
<p>
  <strong>Language:</strong><br>
  <%= @movie.language %>
</p>
<p>
  <strong>Metascore:</strong><br>
  <%= @movie.metascore %>
</p>
<p>
  <strong>Release Date:</strong><br>
  <%= @movie.release_date %>
</p>
</div>


<div class="center">
  <div id="button-add">
    <% if @addedmovie.blank? %>
    <%= render(partial: 'user_movies/added_movie_form', locals: { movie_id: @movie.id})%>
    <% else %>
    <div class="Comments">
      <%= render partial: "user_movies/comments" %>
    </div>
    <br>
    <%= render(partial: 'user_movies/rating_form',  locals: { usermovie: @addedmovie})%>
    <br>
    <%= render(partial: 'user_movies/edit',  locals: { usermovie: @addedmovie}) %>
    <br>
    <%= render(partial: 'user_movies/delete',  locals: { usermovie: @addedmovie, movie_id: @movie_id}) %>
    <br>

    <% end %>
  </div>
  <br><br>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Back', movies_path %>
</div>