config/routes.rb
Rails.application.routes.draw do

  get '/home',      to: 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/search',    to: 'movies#search'
  get '/apicreate', to: 'movies#apicreate'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'log_out', to: 'devise/sessions#destroy'
    get 'edit',    to: 'devise/registrations#edit'
  end

  post 'friendship', to: 'friendships#create'
  delete 'friendship', to: 'friendships#destroy'
  resources :users, only: [:index, :show]
  resources :movies
  resources :user_movies, except: [:destroy, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    respond_to do |format|

      if @friendship.save
        format.js { @success = true }
      else
        format.js { @success = false }
      end

    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find_by(friend_id: params[:friend_id])
    @friendship.destroy
    respond_to do |format|
      format.js { @friend_id = params[:friend_id] }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_add.html.erb
<%= link_to "Add Friend", friendship_path(friend_id: friend_id), method: :post , remote: true %>

app/views/friendships/_delete.html.erb
<%= link_to "Remove Friend", friendship_path(friend_id: friend_id), method: :delete , remote: true %>

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :friendship_user_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id, id: :friendship_friend_id %>
  </div>

  <div class="field">
    <%= form.label :create %>
    <%= form.text_field :create, id: :friendship_create %>
  </div>

  <div class="field">
    <%= form.label :destroy %>
    <%= form.text_field :destroy, id: :friendship_destroy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/create.js.erb
<% if @success %>
  $("#relationship").html("<%= j render(partial: 'friendships/delete', locals: {friend_id: @friendship.friend_id})%>");
<%end%>

app/views/friendships/destroy.js.erb
$("#relationship").html("<%= j render(partial: 'friendships/add', locals: { friend_id: @friend_id})%>");

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>