config/routes.rb
Rails.application.routes.draw do

  get '/home',      to: 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/search',    to: 'movies#search'
  get '/apicreate', to: 'movies#apicreate'

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
    get 'log_out', to: 'devise/sessions#destroy'
    get 'edit',    to: 'devise/registrations#edit'
  end

  post 'friendship', to: 'friendships#create'
  delete 'friendship', to: 'friendships#destroy'
  resources :users, only: [:index, :show]
  resources :movies
  resources :user_movies, except: [:destroy, :show, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Movie Organizer</a>
    by Ewerton Ruiz</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help",   help_path %></li>     
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Movie Organizer", root_path, id: "logo" %>
    <nav>
      <div class="searchboxheader">
        <%= form_tag '/search', method: :get do  %>
          <%= text_field_tag "searchterm", "", placeholder: "Search movies..." %>
        <% end %>
      </div>
      <div style="float: right">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Popular Movies", movies_path %></li>
        <li><%= link_to "My Movies", user_movies_path %></li>
        <li><%= link_to "Friends",  users_path %></li>
        <li><%= link_to "Settings", edit_path %></li>
        <li><%= link_to "Log out",  log_out_path %></li>
      <% else %>
        <li><%= link_to "Movies", movies_path %></li>
        <li><%= link_to "Log in",  sign_in_path %></li>
        <li><%= link_to "Sign Up",  sign_up_path %></li>
         <% end %>
      </ul>
    </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'  %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>